### ISSUE TITLE
Default pager scrolls to the bottom

### ISSUE THREAD

**Issue by tranzystorekk** [tealdeer-rs/tealdeer#361]
When setting `use_pager=true`, the `less -R` default displays short tldr pages scrolled to the bottom:

![obraz](https://github.com/dbrgn/tealdeer/assets/5671049/c90fc440-b7a2-4f10-a482-e48e38488a9f)

This can be fixed with `PAGER="less -R +g"`:

![obraz](https://github.com/dbrgn/tealdeer/assets/5671049/0f37ffc0-deed-4615-9307-6f271def7378)

I'm not sure if modifying the default command is worth it, but setting the global `PAGER` also seems like an overkill, maybe a `TEALDEER_PAGER` variable would be a good middle ground?

**Comment by niklasmohrin** [comment]
Would using an alias work? In bash, you can run `alias tldr="PAGER='less -R +g' tldr"` in your `.bashrc` file, which is where I suppose you would want to set the value of `TEALDEER_PAGER`, if we would support that. Then, all following usages of `tldr` will have the `PAGER` variable set.

**Comment by tranzystorekk** [comment]
Alias is a viable workaround, but a proper `TEALDEER_PAGER` seems like a more user-forward way; similarly `man` has `MANPAGER` and `bat` has `BAT_PAGER`.

**Comment by niklasmohrin** [comment]
Fair enough. We are generally moving more towards `config.toml` over environment variables, so maybe an option there (next to `use_pager`) would be better

**Comment by tranzystorekk** [comment]
With 1.7.0 fresh out of the gate, would we be interested in implementing either of the proposed here solutions?

**Comment by niklasmohrin** [comment]
I am open for adding a setting to the config file. We can discuss the name of the setting can in the corresponding PR, so there is no need to come up with one in order to start working on the feature.

I am a bit hesitant about the environment variable still and would rather not include it for now. (I am thinking about whether or not we should refactor the configuration part of the codebase to have a unified scheme of config variable, environment variable, and CLI flag interaction, but haven't really decided or come up with something)

**Comment by tranzystorekk** [comment]
After some time to play around, I found out I prefer this behavior enforced in all `less` uses (simply set the `LESS="+g"` variable globally), so this issue is moot for me.

Still, thank you for considering this and humoring me :)
